version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hetzner_api_db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: hetzner_api_emulator
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    container_name: hetzner_api_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
